# Goal: Whenever someone changes the python code,
# the linter will check if the syntax, format, indentation (Linting) is correct or not

name: Auto Linter

on:
  push:
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    # this step will automatically clone the code of the current branch into runner
    steps:
      - name: Checkout/clone the code
        uses: actions/checkout@v7

      # this step install linting tool
      - name: Install Linter
        run: pip install ruff
